name: PackyCode Data Collection

on:
  schedule:
    # 每5分钟执行一次数据收集
    - cron: '*/5 * * * *'
    # 每天00:05执行日统计重置
    - cron: '5 0 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  collect-data:
    if: github.event.schedule == '*/5 * * * *' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    
    steps:
      - name: Call Data Collection API
        run: |
          curl -X POST "${{ secrets.API_BASE_URL }}/api/collect" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.API_SECRET }}" \
            --fail --show-error --silent

  daily-reset:
    if: github.event.schedule == '5 0 * * *' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    
    steps:
      - name: Call Daily Reset API
        run: |
          curl -X POST "${{ secrets.API_BASE_URL }}/api/daily-reset" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.API_SECRET }}" \
            --fail --show-error --silent